### PR TITLE
fix for problematic for-in loops

### PR DESCRIPTION
**Pull request by dlueth**
In our case (a legacy project) these for-in loops cause major problems with prototype.js in its latest version and might potentially also cause severe bugs with other libraries. Sadly enough removing prototype.js from our project is not an option :(

### CODE REVIEW

**Comment by sha256** [comment]
@dlueth, in all the loops you've re-written, there's one common mistake:
For example:
`for(let i = 0; fields[i]; i++)` should be `for(let i = 0; i<fields.length; i++)`

**Comment by dlueth** [comment]
Afaik these may only be problematic if falsy values are valid for these arrays, which should not be the case here, correct?

**Comment by dlueth** [comment]
@sha256 Any chance for feedback or merge?

**Comment by DimaGashko** [comment]
Please, never ever use for in for arrays! It's... it's too bad. For in loop ~50 times slower and has other problems.

https://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-a-bad-idea

**Comment by dlueth** [comment]
@sha256 May we assume that this lib is abandoned? No commits, no closed issues, no merged PRs, no further comments from March 2019 to now?

**Comment by DimaGashko** [comment]
@dlueth I don't think so. Some of my PRs were accepted.
p.s. last commit: Jan 9, 2020, not March 2019

**Comment by dlueth** [comment]
Yea, you are right - last commit from @sha256 himself is from march 2019. Anyway, no idea why this one is not getting merged or further discussed on. We still have to stay on our fork or stop using pristine alltogether. The real Problem with for ... in for us still exists and I do not see any points (in this case) where the changed loops would cause any problems.

**Comment by DimaGashko** [comment]
@dlueth sounds familiar (with other lib we used to use)

**Comment by sha256** [comment]
@dlueth, @DimaGashko Sorry, could not look into this earlier. I have added few test cases recently so that new pull requests can be merged quickly. I'll check and merge it asap.

**Comment by dlueth** [comment]
Thx, greatly appreciated!

**Comment by dlueth** [comment]
@sha256 Just one more thing: any ETA for an npm publish for this?

**Comment by sha256** [comment]
@dlueth, published just now :)

**Comment by dlueth** [comment]
@sha256 perfect, thx!

**Pull request merged**
