### PR TITLE
Some more validators

### PR DESCRIPTION
**Pull request by luca-vercelli**
I know that "_The goal of this library is not to provide every possible type of validation_", anyway, I think that some more validators could be useful.
Moreover, the "integer" validator did not work, I fixed that.

Provided validators: **integer**, **zipcode**, **pwdmatch**, **minage**, **validate**

I'm particularly proud of the "validate" validator, that allows writing complex conditions directly in HTML data.

### CODE REVIEW

**Comment by luca-vercelli** [comment]
@xaca I just added something in docs.

I wrote this code a long time ago. Today I realize that it could be more generic. Instead of "pwdmatch" one could implement a more generic "equals" validator, that is satisfied if two fields are equal; and instead of "minage" one could implement a "greater-than" validator, that is satisfied if the field is larger than another one.

**Comment by sha256** [comment]
Hi @luca-vercelli, the problem is, zip code and date format are country specific. Also I'm against adding pwd matching to the library because everyone has different requirement for password format/strength, so they're going to add a custom validator anyway. I think this can be added to the demos but not in the core library.

**Comment by luca-vercelli** [comment]
Hi @sha256 , I see the point. However this library is a little poor of validators, a large effort is required to programmer in order to use it.
Probably, a solution could be as follows.

1. Implement some new validators:  `equals`, `less-than`, `less-or-equal-than`, `greater-than`, `greater-or-equal-then`, `validate`

2. Improve the docs adding some useful, non programmatic, examples, e.g. for zipcode:

`
    <input data-pristine-pattern="/^[0-9]{5}(?:-[0-9]{4})?$/" data-pristine-pattern-message="Invalid ZIP code" ></input>`

for passwords:

`    <input type="password" id="pwd></input>`
`    <input type="password" id="retype-pwd" data-pristine-equals="pwd" data-pristine-equals-message="Passwords don't match"></input>`

and for minimum required age:

`    <input type="integer" data-pristine-greater-or-equal-then="14" data-pristine-equals-message="Users must be at least 14"></input>
`

**Comment by sha256** [comment]
@luca-vercelli, `less-than`, `less-or-equal-than`,  `greater-than`, `greater-or-equal-then` etc all can be achieved using `min`/`max`. Also as `validate` involves using `eval`, I think it's better not to add this to the core.

I think `equals` is a good one. But the attribute value could be like `#attr-id` or `.attr-class` to avoid confusions. e.g. someone may think that input value needs to be equals to the attribute value.

**Comment by luca-vercelli** [comment]
@sha256 `less-than`, in my mind, is not the same as `min`. It's more similar to `equals`: the comparison is done w.r.t another field, not to a constant.

I agree with the "#" notation.

e.g. 

`    <input type="integer" id="first-value"></input>`

`    <input type="integer" id="second-value" data-pristine-greater-than="#first-value" data-pristine-greater-than-message="Second value must be greater than first one" ></input>`

**Comment by sha256** [comment]
Okay, I misunderstood. Do you think `less-than`, `less-or-equal-than`, `greater-than`, `greater-or-equal-then` etc are as useful as the other built-in ones. I can only think of one use case: range. Also use of integer ranges are less than date ranges.  Do you have any more examples in mind where they can be useful?

**Comment by luca-vercelli** [comment]
Well, no, I have no other use cases...

**Comment by luca-vercelli** [comment]
@sha256, if you agree, I could work on this. I could implement (at least) the `equals `validator, and add some more examples in the README.md. (or, there is some better place for examples?)

**Comment by sha256** [comment]
That'd be great. Please for now consider equals only. Other validator would be more useful if they could be used for other input types, e.g. date format. But currently date type isn't built-in because there's no way to custom support date format without using a third party library. 

As for examples, I have added few in demo.md file in gh-pages branch. I think I'd be better to add examples there as the main readme file is already pretty big. We can add a section in the main readme and link all the demos in list. What do you think?

**Comment by xaca** [comment]
> 
> 
> Hi @sha256 , I see the point. However this library is a little poor of validators, a large effort is required to programmer in order to use it.
> Probably, a solution could be as follows.
> 
>     1. Implement some new validators:  `equals`, `less-than`, `less-or-equal-than`, `greater-than`, `greater-or-equal-then`, `validate`
> 
>     2. Improve the docs adding some useful, non programmatic, examples, e.g. for zipcode:
> 
> 
> ` <input data-pristine-pattern="/^[0-9]{5}(?:-[0-9]{4})?$/" data-pristine-pattern-message="Invalid ZIP code" ></input>`
> 
> for passwords:
> 
> ` <input type="password" id="pwd></input>`
> ` <input type="password" id="retype-pwd" data-pristine-equals="pwd" data-pristine-equals-message="Passwords don't match"></input>`
> 
> and for minimum required age:
> 
> ` <input type="integer" data-pristine-min="14" data-pristine-min-message="Users must be at least 14"></input>`

I agree, would be nice if some common validator ara comming with the library. For example match if two fields are equals, or has the same lenght.

**Pull request closed without merging**
